name: Build and Release
on:
  push: { branches: [master] } # develop, 
  #pull_request: { branches: [master] }
  #release: { types: [published] }

env:
  UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
  UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}

jobs:
  buildAndroid:
    name: Build the project
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true
      
      # Cache
      - name: Cache
        uses: actions/cache@v2
        with:
          path: Library
          key: Library
      
      # Build
      - name: Build project
        uses: webbertakken/unity-builder@v1.1
        with:
          unityVersion: 2019.4.6f1
          targetPlatform: Android

      # Output
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Build
          path: build
          
      # Return License
      - name: Return license
        uses: webbertakken/unity-return-license@v1
        if: always()
